services:
  app:
    build:
      args:
        user: bry
        uid: 1000
      context: ./
      dockerfile: .docker/Dockerfile
    image: bry
    container_name: bry-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bry
    ports:
      - "9003:9003"

  db:
    image: postgres:latest
    container_name: bry-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bry
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/volumes/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bry

  nginx:
    image: nginx:alpine
    container_name: bry-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/volumes/nginx:/etc/nginx/conf.d/
    networks:
      - bry

networks:
  bry:
    driver: bridge

volumes:
  postgres_data:
